### ISSUE TITLE
doc link error "404 Not Found"

### ISSUE THREAD

**Issue by xuyangbill** [rustdesk/doc.rustdesk.com#1]
![image](https://user-images.githubusercontent.com/5809774/163495731-e941ec61-1961-499d-aa0f-e2b3dc256c4d.png)
![image](https://user-images.githubusercontent.com/5809774/163495774-8eaa2169-f1ae-40d3-9a18-e623e974a049.png)

**Comment by rustdesk** [comment]
Fixed, Thanks.
