### ISSUE TITLE
The problem of transferring files between Android and PC

### ISSUE THREAD

**Issue by btoget** [rustdesk/doc.rustdesk.com#109]
The PC can transfer files to the mobile phone, but the files on the mobile phone cannot be transferred to the PC
![image](https://user-images.githubusercontent.com/121247398/209173819-e3dc3dac-2581-4e87-b548-0cb7a8152e33.png)
![1](https://user-images.githubusercontent.com/121247398/209173949-dc463b74-dda7-4e05-a22c-f32879d8c13c.png)

**Comment by FoxMiner** [comment]
I have the same problem :(

**Comment by rustdesk** [comment]
try out nightly build both.
