### ISSUE TITLE
Windows Client - Rename for host argument not working

### ISSUE THREAD

**Issue by hvieirapt** [rustdesk/doc.rustdesk.com#136]
Renaming the client .exe file to include the format rustdesk-host=ip/domain.exe not importing custom host config.

**Comment by adminSYS-pl** [comment]
try

rustdesk-host=<host-ip-or-name>,key=<public-key-string>.exe

**Comment by hvieirapt** [comment]
that worked, i was trying to only use the host field.
Thanks.
