### ISSUE TITLE
Docker compose example on tutorial page not the same as on github (encryption problems (-k _))

### ISSUE THREAD

**Issue by Naboo2604** [rustdesk/doc.rustdesk.com#137]
docker compose example on the [tutorial](/https://rustdesk.com/docs/en/self-host/install/) page shows different volumes for hbbs and hbbr:

hbbs section:
    volumes:
      - ./hbbs:/root

hbbr section:
    volumes:
      - ./hbbr:/root
      
...that does not work for me (playing around with copying id files doesnot solved for me) - the [example](https://github.com/rustdesk/rustdesk-server/blob/master/docker-compose.yml) on github point´s both to the same volume:

hbbs section:
    volumes:
      - ./data:/root
      
hbbr section:
    volumes:
      - ./data:/root
      
..that works perfectly.

**Comment by fashberg** [comment]
i've ran into the same problems yesterday. created PR
