### ISSUE TITLE
could not find native static library `opus`

### ISSUE THREAD

**Issue by shanjunmei** [rustdesk/doc.rustdesk.com#155]
even i run the commad  `vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static`
 successfully ,still get  this error when i run `cargo build` or `cargo run`

` vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static
Computing installation plan...
The following packages are already installed:
    libvpx[core]:x64-windows-static -> 1.12.0
    libyuv[core]:x64-windows-static -> 1857
    opus[core]:x64-windows-static -> 1.3.1#9
libvpx:x64-windows-static is already installed
libyuv:x64-windows-static is already installed
opus:x64-windows-static is already installed
Restored 0 package(s) from C:\Users\shanj\AppData\Local\vcpkg\archives in 68.5 us. Use --debug to see more details.
Total install time: 106.1 us
libvpx provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(unofficial-libvpx CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::libvpx::libvpx)

libyuv provides CMake targets:

    find_package(libyuv CONFIG REQUIRED)
    target_link_libraries(main PRIVATE yuv)

    # WARNING
    # You are using MSVC to compile libyuv, which results in a very slow library.
    # MSVC won't compile any of the acceleration codes.
    # See workarounds: https://github.com/microsoft/vcpkg/issues/28446

opus provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(Opus CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Opus::opus)

`

**Comment by ks-zhk** [comment]
set RUSTFLAGS='-L PATH/TO/YOUR/VCPKG/LIB/DIR'
and cargo build or cargo run

**Comment by SergeyDjam** [comment]
> set RUSTFLAGS='-L PATH/TO/YOUR/VCPKG/LIB/DIR' and cargo build or cargo run

no worked
