### ISSUE TITLE
IIS documentation misleading

### ISSUE THREAD

**Issue by stephannn** [rustdesk/doc.rustdesk.com#308]
Hi,
I just finishing setting up the IIS describes as here:
https://github.com/rustdesk/doc.rustdesk.com/blob/master/content/self-host/rustdesk-server-pro/installscript/windows/_index.en.md

and the URL Rewrite section is misleading:

1) First also the _Dynamic Content Compression_ has to be installed as IIS component
2) The third step (Disable dynamic compression under compression) is not under Rules but under the web page itself

3) I had the issue with the 500.52 status code cause by compressed responses. I had to add the mentioned variables:
https://techcommunity.microsoft.com/t5/iis-support-blog/iis-acting-as-reverse-proxy-where-the-problems-start/ba-p/846259

4) Had to change my SSL Settings, but this more like a :
Require SSL -> Ignore

I know, some of the points are individual configuration steps but it would be nice to have them mentioned.

**Comment by dinger1986** [comment]
Thanks for your feedback, I will get that updated

**Comment by dinger1986** [comment]
added PR here, any comments @stephannn https://github.com/rustdesk/doc.rustdesk.com/pull/310/commits/325cb1bf516fe72e3e4c92f075c7c8d6d32c5580

**Comment by stephannn** [comment]
I am sorry that I don't have been specific enough:

Dynamic Content Compression is a Feature:
![image](https://github.com/rustdesk/doc.rustdesk.com/assets/38951729/ab28d742-acf3-49db-9de2-5a6042dc8627)
The other features Application Request Routing URL Rewrite have to be installed by following you links

The *dynamic compression* is not under URL Rewrite:
![image](https://github.com/rustdesk/doc.rustdesk.com/assets/38951729/3a6e2764-e9b3-45ac-b7f8-70f0e9f896f0)

Sorry to be so bothering, just want to help others ;)

**Comment by dinger1986** [comment]
added it in
