### ISSUE TITLE
Adjust the file structure of the docs for Synology DSM

### ISSUE THREAD

**Issue by xlionjuan** [rustdesk/doc.rustdesk.com#355]
Currently, the tutorial of the Synology is based on DSM 6, I want to write the tutorial for DSM 7, which comes with new "Container Manager", it comes with docker-compose within its GUI.

Before I proceed, the file structure need to adjusted.

First, move all current contents in ``synology`` to ``synology/dsm-6``, and new tutorial for DSM 7 put in ``synology/dsm-7``, and the ``weight``(Priority setting for hugo) should lower than dsm-6.

https://github.com/rustdesk/doc.rustdesk.com/tree/master/content/self-host/rustdesk-server-oss/synology

https://rustdesk.com/docs/en/self-host/rustdesk-server-oss/synology

Is this request acceptable?

**Comment by rustdesk** [comment]
Go ahead to move. Thanks.
