### ISSUE TITLE
What is the corect way to use Carnet d'adresses section 

### ISSUE THREAD

**Issue by ammonavis** [rustdesk/doc.rustdesk.com#39]
![image](https://user-images.githubusercontent.com/26895875/174428458-2becbb44-9752-4594-afee-38609dd4d239.png)

How to connect a servver API ? 

A have installed with docker compose my how server : 

version: '3'

networks:
  rustdesk-net:
    external: false

services:
  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r myrustdeck.perso.dmn
    volumes:
      - ./hbbs:/root
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./hbbr:/root
    networks:
      - rustdesk-net
    restart: unless-stopped

**Comment by ammonavis** [comment]
Addional question how tu start rundeck client / server on windows start up 
And is ther a raspberry compatible client?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/wiki/FAQ#change-id-login-and-web-console

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9-raspberry-armhf.deb

**Comment by ammonavis** [comment]
I don't undestand the answer : I want to connect an account to avec all my remote rustdeck
![Capture d’écran 2022-06-19 092507](https://user-images.githubusercontent.com/26895875/174470434-49bda2d7-8fc2-4cac-a327-69e20179a7db.jpg)

Hos to make working the api chiche provide this fonctionnality ? 

is thère a documentation of this api ?
