### ISSUE TITLE
We should hope end users using encryption if possible 

### ISSUE THREAD

**Issue by xlionjuan** [rustdesk/doc.rustdesk.com#403]
https://github.com/rustdesk/doc.rustdesk.com/commit/e5064dce714f986951e21eb3375e70ef577eab8d

I don't think it is a good idea to remove `-k _` for the configuration, because we told where to get the public key.

**Comment by rustdesk** [comment]
'-k" is default to "-" now. https://github.com/rustdesk/rustdesk-server/commit/c4c26dd6d76f00fccfab6e49d55293120d75750e

**Comment by xlionjuan** [comment]
Thanks, I think I misunderstanding the meaning of **"Revert"**.

https://github.com/rustdesk/rustdesk-server/commit/5078a1f7971f4b5a507bd7164f1eb960e5195369
