### ISSUE TITLE
Waiting for image

### ISSUE THREAD

**Issue by Conny-Wang** [rustdesk/doc.rustdesk.com#437]
被控端 4K 分辨率
控制端 1080p
经常性连接成功但是不显示画面如下图：
![微信截图_20240816114704](https://github.com/user-attachments/assets/9a8bc864-b600-43d0-a774-9d02be31f0a2)

**Comment by Conny-Wang** [comment]
切换分辨率也没有用
![微信截图_20240816114813](https://github.com/user-attachments/assets/24cc6382-16af-419a-a0d0-3a8080d9bb79)

**Comment by Conny-Wang** [comment]
切换分辨率也没有用
![微信截图_20240816114813](https://github.com/user-attachments/assets/620584cd-daef-45ab-b351-002ce88869ff)

**Comment by Conny-Wang** [comment]
系统 Win11 x64 >> Win11 X64
版本: 1.2.6
构建日期: 2024-06-23 04:14
双边升级过版本也没有用

**Comment by 21pages** [comment]
Could you contact me with email, `c3VuYm9lYXN5QGdtYWlsLmNvbQo=`, base64.

**Comment by Conny-Wang** [comment]
我已经收到邮件，将会尽快回复~~~
Conny

**Comment by rustdesk** [comment]
Please try out this https://github.com/rustdesk/rustdesk/discussions/9124#discussioncomment-10391439?

**Comment by rustdesk** [comment]
Close and lock to favor #9124
