### ISSUE TITLE
windows exe改名后，提示未安装的版本

### ISSUE THREAD

**Issue by lx1054331851** [rustdesk/doc.rustdesk.com#44]
![image](https://user-images.githubusercontent.com/12423206/178088130-2db0358c-31c5-4b30-9b24-053abcc09643.png)

### 另外，如何判定是否通过自建服务器进行连接的？

**Comment by rustdesk** [comment]
你这个脑洞也是奇葩，不是在安装后的目录里改，是下载后，改了后，安装，怎么判断生效，在文档里有写，有图。

**Comment by lx1054331851** [comment]
也不行，下载后的EXE改名后，双击就不安装了，直接运行了，和上面的截图一模一样。

**Comment by rustdesk** [comment]
点左边的安装按钮

**Comment by rustdesk** [comment]
要是看不到，就先卸载，把安装目录的exe改回rustdesk.exe

**Comment by lx1054331851** [comment]
我全新电脑修改的安装包文件名，也点击了左侧安装按钮。发这个issue主要是一直没法复现文档中的这张图：
![image](https://user-images.githubusercontent.com/12423206/178106944-d967f43f-774f-48f4-8d87-2595ea6b4ce6.png)

about里面看不到host信息。所以就一直不知道是否用的是自建的服务器。

多谢不烦回答

**Comment by rustdesk** [comment]
你漏了key，教材里可是host=...key=...都写了。

**Comment by lx1054331851** [comment]
确实，少了key，以为key可以缺省的。
多谢。
