### ISSUE TITLE
中文文档更正错别字

### ISSUE THREAD

**Issue by Leo-Lionni** [rustdesk/doc.rustdesk.com#443]
```
允许局域网发现。
局域网**法相**后, 如果支持 WOL , 则可使用 WOL 。
```
应更正为`发现`
[here](https://rustdesk.com/docs/zh-cn/self-host/client-configuration/advanced-settings/)

**Comment by Leo-Lionni** [comment]
haha, i'm too young too simple for a little fun.

**Comment by Leo-Lionni** [comment]
> ```
> 允许局域网发现。
> 局域网**法相**后, 如果支持 WOL , 则可使用 WOL 。
> ```
> 
> 应更正为`发现` [here](https://rustdesk.com/docs/zh-cn/self-host/client-configuration/advanced-settings/)

haha, i'm too young too simple for a little fun.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/doc.rustdesk.com/commit/77be346d03f38ecb561f5cd69e7d6d9705e84a8d
