### ISSUE TITLE
QR Code for Mobile Devices - Broken link

### ISSUE THREAD

**Issue by lukebarone** [rustdesk/doc.rustdesk.com#46]
I removed the link in my current pull request as it does not go anywhere.

Is there any update on how to setup the QR code so it can be included in the docs?

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/blob/2f21661b74cec1a8272c458195733089715d9e3b/flutter/lib/pages/scan_page.dart#L132

The format is simple, standard json, e.g.
config={"host": "xxx", "key": "xxx"}
Then goto https://www.qr-code-generator.com/

**Comment by lukebarone** [comment]
> https://github.com/rustdesk/rustdesk/blob/2f21661b74cec1a8272c458195733089715d9e3b/flutter/lib/pages/scan_page.dart#L132
> 
> The format is simple, `prefix+standard json`, e.g. `config={"host": "xxx", "key": "xxx"}` Then goto https://www.qr-code-generator.com/

Awesome, thanks! I updated the docs, another pull request coming in.
