### ISSUE TITLE
Issue with Rustdesk client on Linux Mint.

### ISSUE THREAD

**Issue by Brandters** [rustdesk/doc.rustdesk.com#470]
I've installed the latest version of RustDesk and the program locks when I try to write anything in the program. I can click in the GUI without issues but when if I try to add an ID, it hangs, if I try to add my server, it hangs. 

I use Cinnamon with Xorg, but I also tried the Wayland version but it's the same issue. I can't find anything useful in the logs since the program completely freezes. I can give you logs if any logs syslogs can be useful. I've tested running the client from the terminal, and it points to some problem with Flutter.

This is the closest to an error that I've found.

Gdk-CRITICAL **: 01:13:16.624: gdk_device_get_source:  assertion 'GDK_IS_DEVICE (device)'

**Comment by rustdesk** [comment]
![image](https://github.com/user-attachments/assets/894447cc-3d41-4666-8204-370c5d6377c4)

**Comment by fufesou** [comment]
> Cinnamon with Xorg

@Brandters Hi, could you please give a screenshot of the OS and Window Manager info?

![image](https://github.com/user-attachments/assets/acc66901-85f7-4e6c-9114-5a37fc73d94f)

**Comment by fufesou** [comment]
> `Gdk-CRITICAL **: 01:13:16.624: gdk_device_get_source: assertion 'GDK_IS_DEVICE (device)'`

I've tested `rustdesk-1.3.3-x86_64.deb` on the system above.

I also see this print. But the window works on my machine.

**Comment by Brandters** [comment]
Works with the sciter version.
