### ISSUE TITLE
New feature suggestion: Remote console

### ISSUE THREAD

**Issue by proenotec** [rustdesk/doc.rustdesk.com#63]
From what I have seen, when we connect to a client we have three possibilities; connect to desktop, transfer files or TCP tunnel. 
I think it would be very useful a fourth option that allows you to connect directly to the command console in a similar way to when we login with ssh or telnet. 
This would allow us to solve many problems on remote computers without the need to make a connection to the desktop.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/319

**Comment by proenotec** [comment]
Many thanks for the info!

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/319
