### ISSUE TITLE
文档中的一处错误，容易引起误解

### ISSUE THREAD

**Issue by E5DEV2020** [rustdesk/doc.rustdesk.com#88]
页面：
https://rustdesk.com/docs/zh-cn/self-host/install/#%E6%AD%A5%E9%AA%A43-%E5%9C%A8%E5%AE%A2%E6%88%B7%E7%AB%AF%E8%AE%BE%E7%BD%AE-hbbshbbr-%E5%9C%B0%E5%9D%80
源码：
https://github.com/rustdesk/doc.rustdesk.com/blob/master/content/self-host/install/_index.zh-cn.md

在文档中的“步骤3: 在客户端设置 hbbs/hbbr 地址”部分
有一句  “中继服务器指的是hbbr（**21116**）端口。”
这里 **21116** 应该是勘误，根据上下文推断应该是 **21117**

**Comment by rustdesk** [comment]
yes, Thanks
