### ISSUE TITLE
Synology Docker hbbr container error

### ISSUE THREAD

**Issue by CSM-800** [rustdesk/doc.rustdesk.com#93]
I have everything set up as in the instructions. Everything worked initially. Then I switched off the containers once. Since then only the hbbs container runs correctly. The hbbr container now constantly reports "error: Found argument '-r' which wasn't expected, or isn't valid in this context" and restarts over and over again.

I have rebooted the NAS once and also reinstalled Docker. Again and again I get the error in the hbbr container.

What is the problem?

**Comment by nillebor** [comment]
it works here fine - install as one (s6) oder two container (hbbs+hbbr)
how did you install it?
- manually (task or ssh)
- synology docker GUI
- portainer

**Comment by CSM-800** [comment]
> 
Exactly as described here.
https://rustdesk.com/docs/en/self-host/synogy/

**Comment by nillebor** [comment]
no I have no problems with the installation. i just installed hbbs and hbbr without any problems.

![grafik](https://user-images.githubusercontent.com/59985723/200642266-f1fdd8d9-bed6-47ee-9655-9227cd93dadb.png)

hbbs:
![grafik](https://user-images.githubusercontent.com/59985723/200642802-8b813183-a012-47fa-bb60-a460db10ba68.png)

Hbbr:
![grafik](https://user-images.githubusercontent.com/59985723/200642901-80218ae8-5e72-4185-8b94-221884b7845e.png)

 I'm using rustdes-s6. there you have hbbs+hbbr together in one image.

![grafik](https://user-images.githubusercontent.com/59985723/200643309-a517207d-66d4-4b08-a421-d46fe9d05927.png)
![grafik](https://user-images.githubusercontent.com/59985723/200643744-2d46d059-418f-4e61-b895-242b19288424.png)

**Comment by CSM-800** [comment]
Ich hab dank des Screen das Problem gefunden. Ich die Anleitung falsch verstanden. Dachte der Befehl zum Ausführen wäre wie beim hbbs nur eben mit hbbr zu ersetzten. Hatte also "hbbr -r IP" stehen. Der soll aber nur "hbbr" sein. 

I found the problem thanks to the screen. I misunderstood the instructions. Thought the command to run would be like the hbbs only to be replaced with hbbr. So I had "hbbr -r IP". But it should only be "hbbr".
